export default {
  // 中文字符
  Chinese: /[\u4e00-\u9fa5]/,
  // 双字节字符
  DoubleCharacter: /[^\x00-\xff]/,
  // 中国大陆手机号 (移动/联通/电信)
  Mobile: /^1\d{10}$/,
  // 邮箱
  Email: /[\w!#$%&'*+/=?^_`{|}~-]+(?:\.[\w!#$%&'*+/=?^_`{|}~-]+)*@(?:[\w](?:[\w-]*[\w])?\.)+[\w](?:[\w-]*[\w])?/,
  // 统一资源标识符
  URI: /[a-zA-z]+:\/\/[^\s]*/,
  // 空格
  WHITESPACE: /\s+/g,
  // 统一资源定位符
  URL: /^https?:\/\/[^\s]*$/,
  // QQ号码
  QQ: /[1-9][0-9]{4,}/,
  // 邮政编码
  PostalCode: /[1-9]\d{5}(?!\d)/,
  // 身份证
  IDCard: /^(\d{6})(\d{4})(\d{2})(\d{2})(\d{3})([0-9]|X)$/,
  // 整数
  Integer: /^-?[1-9]\d*$/,
  // 正整数
  PositiveInteger: /^[1-9]\d*$/,
  // 负整数
  NegtiveInteger: /^-[1-9]\d*$/,
  // 非正整数
  NonPositiveInteger: /^-[1-9]\d*|0$/,
  // 非负整数
  NonNegtiveInteger: /(^[1-9]+\d*$)|(^0$)/,
  // 图片
  Image: /.(jpe?g|png)$/i,
  // 字符数字下划线
  Code: /^[a-zA-Z0-9_]\w*$/,
  // 字符数字
  CodeNum: /^[a-zA-Z0-9]\w*$/,
  // 中文，数字英文
  DepartmentName: /^[\u4e00-\u9fa5_a-zA-Z0-9]+$/,
  // 英文
  English: /^[\u4e00-\u9fa5_a-zA-Z]+$/,
  // 色值
  Color: /(^[0-9A-F]{6}$)|(^[0-9A-F]{3}$)/i,
  // 单字节，某些地方需要统计字符串的字节长度
  SingleByte: /[A-Za-z0-9\s]/,
};
